[package]
name = "matrix_mult"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
threads = { path = "../threads" }
util = { path = "../util" }
